name: CI · Shopify (minimal)

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  theme-check:
    name: Theme Check (Liquid)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: gem install theme-check
      - run: theme-check
