name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: Scan code for secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run fast secret grep
        run: |
          set -euo pipefail
          echo "Scanning for likely secrets..."

          # Patterns to check (tune as needed)
          patterns=(
            "-----BEGIN PRIVATE KEY-----"
            "aws_secret_access_key"
            "aws_access_key_id"
            "SENTRY_AUTH_TOKEN"
            "SHOPIFY_CLI_THEME_TOKEN"
            "GH_PAT"
            "GITHUB_TOKEN"
            "API_KEY"
            "API-KEY"
            "PRIVATE_KEY"
            "SECRET"
            "PASSWORD"
            "ACCESS_TOKEN"
            "-----BEGIN RSA PRIVATE KEY-----"
            "AIza[0-9A-Za-z-_]{35}"
            "AIza[0-9A-Za-z-_]{35}"
          )

          matches=0
          for p in "${patterns[@]}"; do
            if git diff --name-only HEAD~1..HEAD | xargs -r grep -nH -E "$p" || true; then
              # Count matches within changed files
              c=$(git diff --name-only HEAD~1..HEAD | xargs -r grep -nH -E "$p" || true | wc -l || true)
              if [ "$c" -gt 0 ]; then
                echo "Found pattern: $p (matches: $c)"
                matches=$((matches + c))
              fi
            fi
          done

          if [ "$matches" -gt 0 ]; then
            echo "Potential secrets detected ($matches matches). Please remove them or move to secrets store."
            exit 1
          fi

          echo "No high-confidence secrets found in the recent changes."

      - name: Run truffleHog deep scan
        id: trufflehog
        run: |
          set -euo pipefail
          echo "Installing truffleHog..."
          python3 -m pip install --user truffleHog
          PATH="$HOME/.local/bin:$PATH"
          echo "Running truffleHog (filesystem) and saving JSON output..."
          trufflehog filesystem --json --exclude-path .git --exclude-path node_modules . > trufflehog-results.json || true

      - name: Upload truffleHog results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
