name: Weekly Sitemap Submit (GSC API)

on:
  schedule:
    # 20:00 Europe/Paris (2 crons pour l'été/hiver car GHA est en UTC)
    - cron: "0 18 * * 0"  # CEST (été)
    - cron: "0 19 * * 0"  # CET  (hiver)
  workflow_dispatch: {}

env:
  # Propriété Search Console (TYPE DOMAIN)
  GSC_PROPERTY: "sc-domain:thepetsociety.paris"

  # Liste des sitemaps à soumettre (tu peux n’en laisser qu’un : sitemap.xml)
  SITEMAP_URLS: >
    https://thepetsociety.paris/sitemap.xml
    https://thepetsociety.paris/sitemap_products_1.xml
    https://thepetsociety.paris/sitemap_collections_1.xml
    https://thepetsociety.paris/sitemap_pages_1.xml
    https://thepetsociety.paris/sitemap_blogs_1.xml

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Auth Google via Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Sécurité : ne lancer que s'il est 20:00 à Paris
      - name: Guard 20:00 Europe/Paris
        run: |
          NOW=$(TZ=Europe/Paris date +%H:%M)
          echo "Current time in Paris: $NOW"
          [ "$NOW" = "20:00" ] || { echo "Not 20:00 Paris time; skipping."; exit 0; }

      - name: Submit sitemap(s) via Search Console API
        env:
          GSC_PROPERTY: ${{ env.GSC_PROPERTY }}
          SITEMAP_URLS: ${{ env.SITEMAP_URLS }}
        run: |
          set -euo pipefail
          ACCESS_TOKEN="$(gcloud auth print-access-token)"

          urlenc() { python3 - <<'PY'
import os, urllib.parse
print(urllib.parse.quote(os.environ["VAL"], safe=""))
PY
          }

          for URL in $SITEMAP_URLS; do
            VAL="$GSC_PROPERTY"; SITE_ENC=$(VAL="$VAL" urlenc)
            VAL="$URL";          FEED_ENC=$(VAL="$VAL" urlenc)
            ENDPOINT="https://www.googleapis.com/webmasters/v3/sites/${SITE_ENC}/sitemaps/${FEED_ENC}"
            echo "PUT $ENDPOINT"
            curl -fsS -X PUT "$ENDPOINT" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              && echo "✅ Submitted $URL" || { echo "❌ Failed $URL"; exit 1; }
          done
