# .github/workflows/weekly-sitemap-submit.yml
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Auth Google via Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # ⬇️ Ne bloque que pour le cron, pas pour workflow_dispatch
      - name: Guard 20:00 Europe/Paris
        if: ${{ github.event_name == 'schedule' }}
        run: |
          NOW=$(TZ=Europe/Paris date +%H:%M)
          echo "Current time in Paris: $NOW"
          [ "$NOW" = "20:00" ] || { echo "Not 20:00 Paris time; skipping."; exit 0; }

      - name: Submit sitemap(s) via Search Console API
        env:
          GSC_PROPERTY: ${{ env.GSC_PROPERTY }}
          SITEMAP_URLS: ${{ env.SITEMAP_URLS }}
        run: |
          set -euo pipefail
          ACCESS_TOKEN="$(gcloud auth print-access-token)"

          urlenc() { python3 - <<'PY'
import os, urllib.parse
print(urllib.parse.quote(os.environ["VAL"], safe=""))
PY
          }

          submit_one () {
            local endpoint="$1"
            local max_attempts=5
            local attempt=1
            local backoff=2
            while :; do
              echo "PUT $endpoint (attempt $attempt/$max_attempts)"
              httpcode=$(curl -sS -o /tmp/res.txt -w "%{http_code}" -X PUT "$endpoint" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Content-Type: application/json" || true)
              if [[ "$httpcode" =~ ^2 ]]; then
                echo "✅ OK ($httpcode)"
                return 0
              fi
              # Retry sur 429/5xx
              if [[ "$httpcode" == "429" || "$httpcode" =~ ^5 ]]; then
                if [ "$attempt" -lt "$max_attempts" ]; then
                  echo "⚠️ $httpcode, retry in ${backoff}s…"
                  sleep "$backoff"
                  attempt=$((attempt+1))
                  backoff=$((backoff*2))
                  continue
                fi
              fi
              echo "❌ Failed ($httpcode)"
              echo "Response:"
              cat /tmp/res.txt || true
              return 1
            done
          }

          for URL in $SITEMAP_URLS; do
            VAL="$GSC_PROPERTY"; SITE_ENC=$(VAL="$VAL" urlenc)
            VAL="$URL";          FEED_ENC=$(VAL="$VAL" urlenc)
            ENDPOINT="https://www.googleapis.com/webmasters/v3/sites/${SITE_ENC}/sitemaps/${FEED_ENC}"
            submit_one "$ENDPOINT"
          done
